name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build -- --configuration production --output-path=dist/portfolio-ilyass --base-href="/portfolio-ilyass/"

      - name: Ensure `index.html` exists
        run: |
          if [ ! -f dist/portfolio-ilyass/index.html ]; then
            echo "Error: index.html not found!"
            exit 1
          fi

      - name: Copy `index.html` to `404.html`
        run: cp dist/portfolio-ilyass/index.html dist/portfolio-ilyass/404.html

      - name: Create `.nojekyll` file
        run: echo > dist/portfolio-ilyass/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/portfolio-ilyass
